# Generated by Django 4.1.4 on 2023-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="users/static/media/products_images/"),
        ),
    ]
